#:schema node_modules/wrangler/config-schema.json
name = "sveltekit-template"
compatibility_date = "2024-12-18"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_flags = [ "nodejs_als" ]

# pnpm dlx wrangler d1 create <project_name>